# Generated by Django 3.2.10 on 2022-01-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencia',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
