# Generated by Django 3.2.10 on 2022-04-06 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0001_initial'),
        ('visitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de saída')),
                ('setores', models.ManyToManyField(to='setores.Setor', verbose_name='Setores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuáripo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Controle de acesso',
                'verbose_name_plural': 'Controles de acessos',
            },
        ),
    ]
