# Generated by Django 3.2.10 on 2022-02-07 21:22

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='cpf'),
        ),
    ]
