# Generated by Django 3.2.10 on 2022-03-31 19:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='fotos_funcionarios', verbose_name='Foto do funcionário'),
        ),
    ]
