# Generated by Django 3.2.10 on 2022-01-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerencias', '0002_gerencia_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencias.gerencia', verbose_name='Gerência')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
